### PR TITLE
Remove non-functioning download instructions

### PR DESCRIPTION
**Pull request by jimoquinn**
Remove non-functioning download instructions from InstallInstructions.vue.  It is confusing when the recommended method to install doesn't work.

### CODE REVIEW

**Comment by AustinCasteel** [comment]
I am ok with removing or commenting out the Naobian section until it is actually ready. However taking out that whole block of code is not good. That removes the platform select which shows raspberry currently as well as the stable or dev build selection. So this change would force people to download the stable builds instead of the newer dev option if they so choose. The only way someone can get it would be if they check bintray or github.

**Comment by jimoquinn** [comment]
Maybe I'm 

> I am ok with removing or commenting out the Naobian section until it is actually ready. However taking out that whole block of code is not good. That removes the platform select which shows raspberry currently as well as the stable or dev build selection. So this change would force people to download the stable builds instead of the newer dev option if they so choose. The only way someone can get it would be if they check bintray or github.

Maybe I'm missing something, but there were no builds available -- stable or dev. Well, let me clarify, I can't locate any .img files which would be appropriate for the Recommend method of installing.  I looked in **/download** and **/download/images** but don't find any.  

Again, I could be out in space somewhere not looking in the right spot, but thought I did a decent job looking for them.  If the .img files are back on the server, then I'm more than happy to add the code back in and point the download to the proper URL so the 404 error goes away.

**Comment by jimoquinn** [comment]
> Maybe I'm
> 
> > I am ok with removing or commenting out the Naobian section until it is actually ready. However taking out that whole block of code is not good. That removes the platform select which shows raspberry currently as well as the stable or dev build selection. So this change would force people to download the stable builds instead of the newer dev option if they so choose. The only way someone can get it would be if they check bintray or github.
> 
> Maybe I'm missing something, but there were no builds available -- stable or dev. Well, let me clarify, I can't locate any .img files which would be appropriate for the Recommend method of installing. I looked in **/download** and **/download/images** but don't find any.
> 
> Again, I could be out in space somewhere not looking in the right spot, but thought I did a decent job looking for them. If the .img files are back on the server, then I'm more than happy to add the code back in and point the download to the proper URL so the 404 error goes away.

I see, totally my mistake.  The "Choose Your Version" controls "Manual Installation" options as well.  My fault and I'll add that code back into the page.

**Comment by AustinCasteel** [comment]
Like I said in the related issue, the Naobian does not exist yet. (There has been many set backs) So even though it is theoretically preferred and recommended it just isn't a thing yet. So removing or commenting out that specifically is fine. As far as the standard stable and dev they are available on github under releases and through bintray. The manual instructions walk you through using bintray but ultimately they are the same. When you select a platform and then select the stable or dev the instructions change based on what was selected.

There are no .img or full "build" files. Naobian with be our pre-made image and the standard stable and dev is just a project folder.

**Comment by AustinCasteel** [comment]
The reason why I did not merge it after the fix was because what you did change was in the right direction but does not actually work. (was it tested?) But today I needed to adjust the install steps and went ahead and implemented the Naobian vue if along with it. So this issue is now resolved.

In other news, the naobian img is progressing once again so hopefully in the not too distant future we will be able to release it!

**Comment by AustinCasteel** [comment]
Closing; issue handled in [PR#23](https://github.com/NaomiProject/naomi-website/pull/23).

**Pull request closed without merging**
